// Generates ecosystem.config.js entries for many bot instances from a single
// fleet.json file — handy when running several WhatsApp numbers (or several
// deployments) from one machine with pm2. For genuinely separate physical
// servers, you don't need this: just clone the project once per server with
// its own .env (see README section 7).
//
// Usage:
//   1. Copy fleet.example.json to fleet.json and fill in your numbers/sessions.
//   2. node scripts/generate-fleet.js
//   3. pm2 start ecosystem.fleet.config.js
const fs = require('fs');
const path = require('path');

const fleetPath = path.join(__dirname, '..', 'fleet.json');
if (!fs.existsSync(fleetPath)) {
  console.error('fleet.json not found. Copy fleet.example.json to fleet.json and fill it in first.');
  process.exit(1);
}

const fleet = JSON.parse(fs.readFileSync(fleetPath, 'utf-8'));
if (!Array.isArray(fleet) || !fleet.length) {
  console.error('fleet.json must be a non-empty array of { "name": "...", "sessionId": "..." } objects.');
  process.exit(1);
}

const apps = fleet.map((entry) => ({
  name: entry.name,
  script: 'index.js',
  autorestart: true,
  watch: false,
  max_memory_restart: '300M',
  env: {
    SESSION_NAME: entry.name,
    SESSION_ID: entry.sessionId || '',
    BOT_NAME: entry.botName || 'JagX',
    OWNER_NUMBER: entry.ownerNumber || '',
  },
}));

const output = `// Auto-generated by scripts/generate-fleet.js from fleet.json — do not edit by hand.
// Run: pm2 start ecosystem.fleet.config.js
module.exports = { apps: ${JSON.stringify(apps, null, 2)} };
`;

fs.writeFileSync(path.join(__dirname, '..', 'ecosystem.fleet.config.js'), output);
console.log(`Generated ecosystem.fleet.config.js with ${apps.length} instance(s).`);
console.log('Run: pm2 start ecosystem.fleet.config.js');
